version: '3.8'

services:
  etherscan-test:
    image: node:22-alpine
    container_name: etherscan-test-container
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    user: "1000:1000"
    command: >
      sh -c "npm install && npm run start:dev"
    env_file: './config/.dev.env'
    restart: unless-stopped
